/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin-notifications'
import { Route as AuthenticatedAiDiagnosticsRouteImport } from './routes/_authenticated/ai-diagnostics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDiagnosticsRouteImport } from './routes/_authenticated/diagnostics'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedUploadsRouteImport } from './routes/_authenticated/uploads'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes.index'
import { Route as AuthenticatedNotesIdRouteImport } from './routes/_authenticated/notes.$id'
import { Route as AuthenticatedNotesNewRouteImport } from './routes/_authenticated/notes.new'
import { Route as AuthenticatedPptIndexRouteImport } from './routes/_authenticated/ppt.index'
import { Route as AuthenticatedPptIdRouteImport } from './routes/_authenticated/ppt.$id'
import { Route as AuthenticatedQuestionBankIndexRouteImport } from './routes/_authenticated/question-bank.index'
import { Route as AuthenticatedQuestionBankIdRouteImport } from './routes/_authenticated/question-bank.$id'
import { Route as AuthenticatedQuestionPapersIndexRouteImport } from './routes/_authenticated/question-papers.index'
import { Route as AuthenticatedQuestionPapersIdRouteImport } from './routes/_authenticated/question-papers.$id'
import { Route as ApiPublicHooksDailyPushRouteImport } from './routes/api/public/hooks/daily-push'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/admin-notifications',
    path: '/admin-notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiDiagnosticsRoute =
  AuthenticatedAiDiagnosticsRouteImport.update({
    id: '/ai-diagnostics',
    path: '/ai-diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticsRoute =
  AuthenticatedDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUploadsRoute = AuthenticatedUploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesIdRoute = AuthenticatedNotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotesNewRoute = AuthenticatedNotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPptIndexRoute = AuthenticatedPptIndexRouteImport.update({
  id: '/ppt/',
  path: '/ppt/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPptIdRoute = AuthenticatedPptIdRouteImport.update({
  id: '/ppt/$id',
  path: '/ppt/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuestionBankIndexRoute =
  AuthenticatedQuestionBankIndexRouteImport.update({
    id: '/question-bank/',
    path: '/question-bank/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionBankIdRoute =
  AuthenticatedQuestionBankIdRouteImport.update({
    id: '/question-bank/$id',
    path: '/question-bank/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionPapersIndexRoute =
  AuthenticatedQuestionPapersIndexRouteImport.update({
    id: '/question-papers/',
    path: '/question-papers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestionPapersIdRoute =
  AuthenticatedQuestionPapersIdRouteImport.update({
    id: '/question-papers/$id',
    path: '/question-papers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksDailyPushRoute = ApiPublicHooksDailyPushRouteImport.update({
  id: '/api/public/hooks/daily-push',
  path: '/api/public/hooks/daily-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-notifications': typeof AuthenticatedAdminNotificationsRoute
  '/ai-diagnostics': typeof AuthenticatedAiDiagnosticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/uploads': typeof AuthenticatedUploadsRoute
  '/notes/$id': typeof AuthenticatedNotesIdRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/ppt/$id': typeof AuthenticatedPptIdRoute
  '/question-bank/$id': typeof AuthenticatedQuestionBankIdRoute
  '/question-papers/$id': typeof AuthenticatedQuestionPapersIdRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
  '/ppt/': typeof AuthenticatedPptIndexRoute
  '/question-bank/': typeof AuthenticatedQuestionBankIndexRoute
  '/question-papers/': typeof AuthenticatedQuestionPapersIndexRoute
  '/api/public/hooks/daily-push': typeof ApiPublicHooksDailyPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin-notifications': typeof AuthenticatedAdminNotificationsRoute
  '/ai-diagnostics': typeof AuthenticatedAiDiagnosticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/uploads': typeof AuthenticatedUploadsRoute
  '/notes/$id': typeof AuthenticatedNotesIdRoute
  '/notes/new': typeof AuthenticatedNotesNewRoute
  '/ppt/$id': typeof AuthenticatedPptIdRoute
  '/question-bank/$id': typeof AuthenticatedQuestionBankIdRoute
  '/question-papers/$id': typeof AuthenticatedQuestionPapersIdRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
  '/ppt': typeof AuthenticatedPptIndexRoute
  '/question-bank': typeof AuthenticatedQuestionBankIndexRoute
  '/question-papers': typeof AuthenticatedQuestionPapersIndexRoute
  '/api/public/hooks/daily-push': typeof ApiPublicHooksDailyPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin-notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/ai-diagnostics': typeof AuthenticatedAiDiagnosticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostics': typeof AuthenticatedDiagnosticsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/uploads': typeof AuthenticatedUploadsRoute
  '/_authenticated/notes/$id': typeof AuthenticatedNotesIdRoute
  '/_authenticated/notes/new': typeof AuthenticatedNotesNewRoute
  '/_authenticated/ppt/$id': typeof AuthenticatedPptIdRoute
  '/_authenticated/question-bank/$id': typeof AuthenticatedQuestionBankIdRoute
  '/_authenticated/question-papers/$id': typeof AuthenticatedQuestionPapersIdRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
  '/_authenticated/ppt/': typeof AuthenticatedPptIndexRoute
  '/_authenticated/question-bank/': typeof AuthenticatedQuestionBankIndexRoute
  '/_authenticated/question-papers/': typeof AuthenticatedQuestionPapersIndexRoute
  '/api/public/hooks/daily-push': typeof ApiPublicHooksDailyPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin-notifications'
    | '/ai-diagnostics'
    | '/dashboard'
    | '/diagnostics'
    | '/notifications'
    | '/profile'
    | '/reminders'
    | '/timetable'
    | '/uploads'
    | '/notes/$id'
    | '/notes/new'
    | '/ppt/$id'
    | '/question-bank/$id'
    | '/question-papers/$id'
    | '/notes/'
    | '/ppt/'
    | '/question-bank/'
    | '/question-papers/'
    | '/api/public/hooks/daily-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin-notifications'
    | '/ai-diagnostics'
    | '/dashboard'
    | '/diagnostics'
    | '/notifications'
    | '/profile'
    | '/reminders'
    | '/timetable'
    | '/uploads'
    | '/notes/$id'
    | '/notes/new'
    | '/ppt/$id'
    | '/question-bank/$id'
    | '/question-papers/$id'
    | '/notes'
    | '/ppt'
    | '/question-bank'
    | '/question-papers'
    | '/api/public/hooks/daily-push'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin-notifications'
    | '/_authenticated/ai-diagnostics'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostics'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/reminders'
    | '/_authenticated/timetable'
    | '/_authenticated/uploads'
    | '/_authenticated/notes/$id'
    | '/_authenticated/notes/new'
    | '/_authenticated/ppt/$id'
    | '/_authenticated/question-bank/$id'
    | '/_authenticated/question-papers/$id'
    | '/_authenticated/notes/'
    | '/_authenticated/ppt/'
    | '/_authenticated/question-bank/'
    | '/_authenticated/question-papers/'
    | '/api/public/hooks/daily-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksDailyPushRoute: typeof ApiPublicHooksDailyPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-notifications': {
      id: '/_authenticated/admin-notifications'
      path: '/admin-notifications'
      fullPath: '/admin-notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-diagnostics': {
      id: '/_authenticated/ai-diagnostics'
      path: '/ai-diagnostics'
      fullPath: '/ai-diagnostics'
      preLoaderRoute: typeof AuthenticatedAiDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnostics': {
      id: '/_authenticated/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AuthenticatedDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/uploads': {
      id: '/_authenticated/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof AuthenticatedUploadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/$id': {
      id: '/_authenticated/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof AuthenticatedNotesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/new': {
      id: '/_authenticated/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof AuthenticatedNotesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ppt/': {
      id: '/_authenticated/ppt/'
      path: '/ppt'
      fullPath: '/ppt/'
      preLoaderRoute: typeof AuthenticatedPptIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ppt/$id': {
      id: '/_authenticated/ppt/$id'
      path: '/ppt/$id'
      fullPath: '/ppt/$id'
      preLoaderRoute: typeof AuthenticatedPptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/question-bank/': {
      id: '/_authenticated/question-bank/'
      path: '/question-bank'
      fullPath: '/question-bank/'
      preLoaderRoute: typeof AuthenticatedQuestionBankIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/question-bank/$id': {
      id: '/_authenticated/question-bank/$id'
      path: '/question-bank/$id'
      fullPath: '/question-bank/$id'
      preLoaderRoute: typeof AuthenticatedQuestionBankIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/question-papers/': {
      id: '/_authenticated/question-papers/'
      path: '/question-papers'
      fullPath: '/question-papers/'
      preLoaderRoute: typeof AuthenticatedQuestionPapersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/question-papers/$id': {
      id: '/_authenticated/question-papers/$id'
      path: '/question-papers/$id'
      fullPath: '/question-papers/$id'
      preLoaderRoute: typeof AuthenticatedQuestionPapersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/daily-push': {
      id: '/api/public/hooks/daily-push'
      path: '/api/public/hooks/daily-push'
      fullPath: '/api/public/hooks/daily-push'
      preLoaderRoute: typeof ApiPublicHooksDailyPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAiDiagnosticsRoute: typeof AuthenticatedAiDiagnosticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticsRoute: typeof AuthenticatedDiagnosticsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedUploadsRoute: typeof AuthenticatedUploadsRoute
  AuthenticatedNotesIdRoute: typeof AuthenticatedNotesIdRoute
  AuthenticatedNotesNewRoute: typeof AuthenticatedNotesNewRoute
  AuthenticatedPptIdRoute: typeof AuthenticatedPptIdRoute
  AuthenticatedQuestionBankIdRoute: typeof AuthenticatedQuestionBankIdRoute
  AuthenticatedQuestionPapersIdRoute: typeof AuthenticatedQuestionPapersIdRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
  AuthenticatedPptIndexRoute: typeof AuthenticatedPptIndexRoute
  AuthenticatedQuestionBankIndexRoute: typeof AuthenticatedQuestionBankIndexRoute
  AuthenticatedQuestionPapersIndexRoute: typeof AuthenticatedQuestionPapersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAiDiagnosticsRoute: AuthenticatedAiDiagnosticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticsRoute: AuthenticatedDiagnosticsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedUploadsRoute: AuthenticatedUploadsRoute,
  AuthenticatedNotesIdRoute: AuthenticatedNotesIdRoute,
  AuthenticatedNotesNewRoute: AuthenticatedNotesNewRoute,
  AuthenticatedPptIdRoute: AuthenticatedPptIdRoute,
  AuthenticatedQuestionBankIdRoute: AuthenticatedQuestionBankIdRoute,
  AuthenticatedQuestionPapersIdRoute: AuthenticatedQuestionPapersIdRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
  AuthenticatedPptIndexRoute: AuthenticatedPptIndexRoute,
  AuthenticatedQuestionBankIndexRoute: AuthenticatedQuestionBankIndexRoute,
  AuthenticatedQuestionPapersIndexRoute: AuthenticatedQuestionPapersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksDailyPushRoute: ApiPublicHooksDailyPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
